name: charge_wallet_sdk
version: 0.0.2+4
homepage: https://docs.chargeweb3.com/docs/overview-2
repository: https://github.com/fuseio/charge_wallet_sdk
description: SDK for Charge Wallet API
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  retrofit: ^3.0.1+1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  path: ^1.8.0
  gql: ^0.13.1
  bip32: ^2.0.0
  bip39: ^1.0.6
  hex: ^0.2.0
  http: ^0.13.5
  web3dart: ^2.3.5
  graphql: ^5.1.1
  decimal: ^2.3.0
  dio: ^4.0.6
dev_dependencies:
  retrofit_generator: ^4.0.3+1
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
